Abort rebase for branches where it can't be done automatically

diff --git a/bin/executable_git-rebase-all b/bin/executable_git-rebase-all
--- a/bin/executable_git-rebase-all
+++ b/bin/executable_git-rebase-all
@@ -11,5 +11,5 @@ for branch in $(git for-each-ref --format='%(refname:short)' refs/heads); do
     if [ "$branch" = "$upstream" ]; then
         continue
     fi
-    git rebase $upstream $branch
+    git rebase $upstream $branch || (echo "Cannot rebase $branch automatically"; git rebase --abort)
 done
